//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.14.5.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace System.ComponentModel
{
    internal class DataAnnotations
    {
        internal class RequiredAttribute : Attribute
        {
            public bool AllowEmptyStrings { get; set; }
        }
    }
}